#!/usr/bin/env bash
# Installs nginc on web server

sudo apt-get update
sudo apt-get install -y nginx

# allowing nginx on port 80
sudo ufw allow 'Nginx HTTP'


echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service ngnix reload
